### ISSUE TITLE
【框架2.0】插件注册及管理功能汇总

### ISSUE THREAD

**Issue by irvinezhao** [WeBankPartners/wecube-platform#285]
**描述您的需求**  
为满足项目2.0架构，需要对现有的插件注册功能进行重构增强。
新的插件注册功能注册的配置文件需要包括以下模块的信息：
- [x] 依赖分析（子任务链接为：前端: #286 ）
- [x] 菜单注入（子任务链接为：前端: #287 ）
- [x] 数据模型（子任务链接为：前端: #288  后端: #132  ）
- [x] 系统参数（子任务链接为：前端: #289 ）
- [x] 权限设定（子任务链接为：前端: #290 ）
- [x] 运行资源（子任务链接为：前端: #314 ）
还有现有的插件注册管理功能重构：
- [x] 插件注册功能重构（子任务链接为：前端: #292）

并且将原来的查看运行实例、查看日志功能增强为：

- [x] 运行管理功能（子任务链接为： #291 ）

**附加**
更新设计稿
[插件注册0.2.zip](https://github.com/WeBankPartners/wecube-platform/files/3629126/0.2.zip)
